// <auto-generated>
//     Generated by PaL.X build task.
//     Runtime version: 9.0
// </auto-generated>

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.Resources;

namespace PaL.X.Client.Properties
{
    [GeneratedCode("PaL.X.Generator", "1.0")]
    [DebuggerNonUserCode]
    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager = new ResourceManager("PaL.X.Client.Properties.Resources", typeof(Resources).Assembly);
        private static CultureInfo? _resourceCulture;

        internal static ResourceManager ResourceManager => _resourceManager;

        internal static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        internal static Bitmap? GetBitmap(string resourceName)
        {
            return ResourceManager.GetObject(resourceName, _resourceCulture) as Bitmap;
        }

        internal static object? GetObject(string resourceName)
        {
            return ResourceManager.GetObject(resourceName, _resourceCulture);
        }
    }
}
